site_name: SimpleLogin Docs
site_url: https://simplelogin.io/docs/
site_description: Receive and send emails anonymously.
site_author: SimpleLogin

# Repository
repo_name: simple-login/documentation
repo_url: https://github.com/simple-login/documentation
copyright: SimpleLogin is an open-source email alias solution to protect your email address from spam and more.



theme:
  name: material
  palette:
    - scheme: default
      primary: white
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  font: false

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

nav:
  - Welcome: index.md
  - Getting started:
    - Register Account: getting-started/register-account.md
    - Create Aliases: getting-started/create-alias.md
    - Send emails from your alias: getting-started/send-email.md
    - Block sender: getting-started/block-sender.md
    - Reverse alias: getting-started/reverse-alias.md
    - One-click unsubscribe: getting-started/one-click-unsubscribe.md
    - Delete an alias: getting-started/delete-alias.md
    - Transfer an alias: getting-started/transfer-alias.md
    - Anti-phishing: getting-started/anti-phishing.md
    - Other email alias service: getting-started/compatibility-email-alias.md
    - Troubleshooting: getting-started/troubleshooting.md
  - Custom Domain:
    - Add a Custom Domain: custom-domain/add-domain.md
    - Manage your domain: custom-domain/manage-domain.md
    - Domain Registrars:
      - NameCheap: custom-domain/registrars/namecheap/namecheap.md
      - NameCheap (subdomain): custom-domain/registrars/namecheap/namecheap-subdomain.md
      - GoDaddy: custom-domain/registrars/godaddy/godaddy.md
      - Google: custom-domain/registrars/google/google.md

  - Subdomain:
    - Create a subdomain: subdomain/new.md
    - Delete a subdomain: subdomain/delete.md
    - Manage your subdomain: subdomain/manage.md

  - Directory:
    - Create a directory: directory/new.md

  - Mailboxes:
    - Add a new mailbox: mailbox/add-mailbox.md

  - Subscription:
    - Student discount: subscription/student-discount.md
    - Family discount: subscription/family-plan.md

  - SIWSL:
    - Welcome: siwsl/intro.md
    - App: siwsl/app.md
    - Guides:
      - Frontend JS: siwsl/frontend-js.md
      - Flask (Python): siwsl/flask.md
      - Django (Python): siwsl/django.md
      - Passport (Node.js): siwsl/passport.md
      - Discourse: siwsl/discourse.md
    - Code Flow - the raw way: siwsl/code-flow.md
    - Implicit Flow - the raw way: siwsl/implicit-flow.md
    - Error Codes: siwsl/errors.md
